title: Cardano Foundation
description: Blockchain Technology | CryptoCurrency Software
baseurl: ""
url: "http://cardanofoundation.org"
include: ["_pages"]
permalink: /:title

markdown: kramdown
array: []

gems:           ['jekyll-paginate', 'jekyll-multiple-languages']
# gems:           ['jekyll-multiple-languages']

languages:          ['en', 'ja', 'cn']
language_default:   'en'

